name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   if: runner.os == 'Windows'
    #   with:
    #     name: spnego-proxy-${{ runner.os }}
    #     path: spnego-proxy.exe

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   if: runner.os == 'macOS'
    #   with:
    #     name: spnego-proxy-${{ runner.os }}
    #     path: spnego-proxy